services:
  api:
    image: docker.io/vyyy/simple-backend:latest
    container_name: simple_backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge